[package]
name = "omc-cli"
description = "OMC package-manager prototype CLI"
edition.workspace = true
license.workspace = true
version.workspace = true

[[bin]]
name = "omc"
path = "src/main.rs"

[[bin]]
name = "npm"
path = "src/bin/npm.rs"

[[bin]]
name = "pip"
path = "src/bin/pip.rs"

[[bin]]
name = "pip3"
path = "src/bin/pip3.rs"

[[bin]]
name = "npx"
path = "src/bin/npx.rs"

[dependencies]
clap = { version = "4", features = ["derive"] }
omc-cap = { path = "../omc-cap" }
omc-registry = { path = "../omc-registry" }
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls"] }
serde_json = "1"
thiserror = "2"
