[package]
name = "omc-cli"
description = "OMC package-manager prototype CLI"
edition.workspace = true
license.workspace = true
version.workspace = true

[[bin]]
name = "omc"
path = "src/main.rs"

[[bin]]
name = "npm"
path = "src/bin/npm.rs"

[[bin]]
name = "pip"
path = "src/bin/pip.rs"

[[bin]]
name = "pip3"
path = "src/bin/pip3.rs"

[[bin]]
name = "npx"
path = "src/bin/npx.rs"

[[bin]]
name = "node"
path = "src/bin/node.rs"

[[bin]]
name = "python"
path = "src/bin/python.rs"

[[bin]]
name = "python3"
path = "src/bin/python3.rs"

[[bin]]
name = "twine"
path = "src/bin/twine.rs"

[dependencies]
base64 = "0.22"
chrono = { version = "0.4", default-features = false, features = ["clock"] }
clap = { version = "4", features = ["derive"] }
flate2 = "1"
omc-cap = { path = "../omc-cap" }
omc-registry = { path = "../omc-registry" }
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls"] }
serde_json = "1"
sha2 = "0.10"
tar = "0.4"
thiserror = "2"
toml = "0.8"
zip = { version = "2", default-features = false, features = ["deflate"] }
